// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/commons.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditUpdaterEnum int32

const (
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_UNSPECIFIED AuditUpdaterEnum = 0
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_FRONTEND    AuditUpdaterEnum = 1
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_SYSOPS      AuditUpdaterEnum = 2
)

// Enum value maps for AuditUpdaterEnum.
var (
	AuditUpdaterEnum_name = map[int32]string{
		0: "AUDIT_UPDATER_ENUM_UNSPECIFIED",
		1: "AUDIT_UPDATER_ENUM_FRONTEND",
		2: "AUDIT_UPDATER_ENUM_SYSOPS",
	}
	AuditUpdaterEnum_value = map[string]int32{
		"AUDIT_UPDATER_ENUM_UNSPECIFIED": 0,
		"AUDIT_UPDATER_ENUM_FRONTEND":    1,
		"AUDIT_UPDATER_ENUM_SYSOPS":      2,
	}
)

func (x AuditUpdaterEnum) Enum() *AuditUpdaterEnum {
	p := new(AuditUpdaterEnum)
	*p = x
	return p
}

func (x AuditUpdaterEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditUpdaterEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_commons_proto_enumTypes[0].Descriptor()
}

func (AuditUpdaterEnum) Type() protoreflect.EnumType {
	return &file_v1_commons_proto_enumTypes[0]
}

func (x AuditUpdaterEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditUpdaterEnum.Descriptor instead.
func (AuditUpdaterEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_commons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Pagination) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Props         map[string]string      `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	SoftDelete    *bool                  `protobuf:"varint,6,opt,name=softDelete,proto3,oneof" json:"softDelete,omitempty"`
	UpdatedBy     *string                `protobuf:"bytes,500,opt,name=updatedBy,proto3,oneof" json:"updatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,501,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_v1_commons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetSoftDelete() bool {
	if x != nil && x.SoftDelete != nil {
		return *x.SoftDelete
	}
	return false
}

func (x *Item) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_v1_commons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_v1_commons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Filter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Filter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Filter) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_v1_commons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{4}
}

func (x *Search) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Search) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Search) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_v1_commons_proto protoreflect.FileDescriptor

const file_v1_commons_proto_rawDesc = "" +
	"\n" +
	"\x10v1/commons.proto\x12\tlistah.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\n" +
	"Pagination\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"\xf6\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x120\n" +
	"\x05props\x18\x04 \x03(\v2\x1a.listah.v1.Item.PropsEntryR\x05props\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12#\n" +
	"\n" +
	"softDelete\x18\x06 \x01(\bH\x00R\n" +
	"softDelete\x88\x01\x01\x12\"\n" +
	"\tupdatedBy\x18\xf4\x03 \x01(\tH\x01R\tupdatedBy\x88\x01\x01\x12>\n" +
	"\tupdatedAt\x18\xf5\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tupdatedAt\x88\x01\x01\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_softDeleteB\f\n" +
	"\n" +
	"_updatedByB\f\n" +
	"\n" +
	"_updatedAt\"W\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"n\n" +
	"\x06Filter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"J\n" +
	"\x06Search\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x03 \x03(\tR\afilters*v\n" +
	"\x10AuditUpdaterEnum\x12\"\n" +
	"\x1eAUDIT_UPDATER_ENUM_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAUDIT_UPDATER_ENUM_FRONTEND\x10\x01\x12\x1d\n" +
	"\x19AUDIT_UPDATER_ENUM_SYSOPS\x10\x02B)Z'cornucopia/listah/internal/pkg/proto/v1b\x06proto3"

var (
	file_v1_commons_proto_rawDescOnce sync.Once
	file_v1_commons_proto_rawDescData []byte
)

func file_v1_commons_proto_rawDescGZIP() []byte {
	file_v1_commons_proto_rawDescOnce.Do(func() {
		file_v1_commons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_commons_proto_rawDesc), len(file_v1_commons_proto_rawDesc)))
	})
	return file_v1_commons_proto_rawDescData
}

var file_v1_commons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_commons_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_commons_proto_goTypes = []any{
	(AuditUpdaterEnum)(0),         // 0: listah.v1.AuditUpdaterEnum
	(*Pagination)(nil),            // 1: listah.v1.Pagination
	(*Item)(nil),                  // 2: listah.v1.Item
	(*Tag)(nil),                   // 3: listah.v1.Tag
	(*Filter)(nil),                // 4: listah.v1.Filter
	(*Search)(nil),                // 5: listah.v1.Search
	nil,                           // 6: listah.v1.Item.PropsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_v1_commons_proto_depIdxs = []int32{
	6, // 0: listah.v1.Item.props:type_name -> listah.v1.Item.PropsEntry
	7, // 1: listah.v1.Item.updatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_commons_proto_init() }
func file_v1_commons_proto_init() {
	if File_v1_commons_proto != nil {
		return
	}
	file_v1_commons_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_commons_proto_rawDesc), len(file_v1_commons_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_commons_proto_goTypes,
		DependencyIndexes: file_v1_commons_proto_depIdxs,
		EnumInfos:         file_v1_commons_proto_enumTypes,
		MessageInfos:      file_v1_commons_proto_msgTypes,
	}.Build()
	File_v1_commons_proto = out.File
	file_v1_commons_proto_goTypes = nil
	file_v1_commons_proto_depIdxs = nil
}
