// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/commons.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditUpdaterEnum int32

const (
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_UNSPECIFIED AuditUpdaterEnum = 0
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_FRONTEND    AuditUpdaterEnum = 1
	AuditUpdaterEnum_AUDIT_UPDATER_ENUM_SYSOPS      AuditUpdaterEnum = 2
)

// Enum value maps for AuditUpdaterEnum.
var (
	AuditUpdaterEnum_name = map[int32]string{
		0: "AUDIT_UPDATER_ENUM_UNSPECIFIED",
		1: "AUDIT_UPDATER_ENUM_FRONTEND",
		2: "AUDIT_UPDATER_ENUM_SYSOPS",
	}
	AuditUpdaterEnum_value = map[string]int32{
		"AUDIT_UPDATER_ENUM_UNSPECIFIED": 0,
		"AUDIT_UPDATER_ENUM_FRONTEND":    1,
		"AUDIT_UPDATER_ENUM_SYSOPS":      2,
	}
)

func (x AuditUpdaterEnum) Enum() *AuditUpdaterEnum {
	p := new(AuditUpdaterEnum)
	*p = x
	return p
}

func (x AuditUpdaterEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditUpdaterEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_commons_proto_enumTypes[0].Descriptor()
}

func (AuditUpdaterEnum) Type() protoreflect.EnumType {
	return &file_v1_commons_proto_enumTypes[0]
}

func (x AuditUpdaterEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditUpdaterEnum.Descriptor instead.
func (AuditUpdaterEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{0}
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Props         []string               `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,7,opt,name=softDelete,proto3" json:"softDelete,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,500,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,501,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_v1_commons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetProps() []string {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Tag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Tag) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

func (x *Tag) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Tag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TagProperty1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TagObjs       []*Tag                 `protobuf:"bytes,3,rep,name=tagObjs,proto3" json:"tagObjs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagProperty1) Reset() {
	*x = TagProperty1{}
	mi := &file_v1_commons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagProperty1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagProperty1) ProtoMessage() {}

func (x *TagProperty1) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagProperty1.ProtoReflect.Descriptor instead.
func (*TagProperty1) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{1}
}

func (x *TagProperty1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TagProperty1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagProperty1) GetTagObjs() []*Tag {
	if x != nil {
		return x.TagObjs
	}
	return nil
}

type InnerPropTagMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]*Tag        `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerPropTagMap) Reset() {
	*x = InnerPropTagMap{}
	mi := &file_v1_commons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerPropTagMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerPropTagMap) ProtoMessage() {}

func (x *InnerPropTagMap) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerPropTagMap.ProtoReflect.Descriptor instead.
func (*InnerPropTagMap) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{2}
}

func (x *InnerPropTagMap) GetValue() map[string]*Tag {
	if x != nil {
		return x.Value
	}
	return nil
}

type MapObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapObj) Reset() {
	*x = MapObj{}
	mi := &file_v1_commons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapObj) ProtoMessage() {}

func (x *MapObj) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapObj.ProtoReflect.Descriptor instead.
func (*MapObj) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{3}
}

func (x *MapObj) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapObj) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_v1_commons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{4}
}

func (x *StringList) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type TagPropertyMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]*StringList `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagPropertyMap) Reset() {
	*x = TagPropertyMap{}
	mi := &file_v1_commons_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagPropertyMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagPropertyMap) ProtoMessage() {}

func (x *TagPropertyMap) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagPropertyMap.ProtoReflect.Descriptor instead.
func (*TagPropertyMap) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{5}
}

func (x *TagPropertyMap) GetValue() map[string]*StringList {
	if x != nil {
		return x.Value
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Props         map[string]string      `protobuf:"bytes,6,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SoftDelete    bool                   `protobuf:"varint,7,opt,name=softDelete,proto3" json:"softDelete,omitempty"`
	TagObjs       []*Tag                 `protobuf:"bytes,8,rep,name=tagObjs,proto3" json:"tagObjs,omitempty"`
	PropObjs      []*MapObj              `protobuf:"bytes,9,rep,name=propObjs,proto3" json:"propObjs,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,500,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,501,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_v1_commons_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Item) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

func (x *Item) GetTagObjs() []*Tag {
	if x != nil {
		return x.TagObjs
	}
	return nil
}

func (x *Item) GetPropObjs() []*MapObj {
	if x != nil {
		return x.PropObjs
	}
	return nil
}

func (x *Item) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,7,opt,name=softDelete,proto3" json:"softDelete,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,500,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,501,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_v1_commons_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{7}
}

func (x *Filter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Filter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Filter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Filter) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Filter) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

func (x *Filter) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Filter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_v1_commons_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{8}
}

func (x *Search) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Search) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Search) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Volume        int64                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_commons_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{9}
}

func (x *Pagination) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Pagination) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type ReadQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadQuery) Reset() {
	*x = ReadQuery{}
	mi := &file_v1_commons_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadQuery) ProtoMessage() {}

func (x *ReadQuery) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadQuery.ProtoReflect.Descriptor instead.
func (*ReadQuery) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{10}
}

func (x *ReadQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReadQuery) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReadReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReference) Reset() {
	*x = ReadReference{}
	mi := &file_v1_commons_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReference) ProtoMessage() {}

func (x *ReadReference) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReference.ProtoReflect.Descriptor instead.
func (*ReadReference) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{11}
}

func (x *ReadReference) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *ReadReference) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *ReadQuery             `protobuf:"bytes,500,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,501,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Reference     *ReadReference         `protobuf:"bytes,502,opt,name=reference,proto3" json:"reference,omitempty"`
	Title         string                 `protobuf:"bytes,503,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_v1_commons_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commons_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_v1_commons_proto_rawDescGZIP(), []int{12}
}

func (x *ReadRequest) GetQuery() *ReadQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ReadRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ReadRequest) GetReference() *ReadReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ReadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_v1_commons_proto protoreflect.FileDescriptor

const file_v1_commons_proto_rawDesc = "" +
	"\n" +
	"\x10v1/commons.proto\x12\tlistah.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05props\x18\x04 \x03(\tR\x05props\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"softDelete\x18\a \x01(\bR\n" +
	"softDelete\x12\x1d\n" +
	"\tupdatedBy\x18\xf4\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\tupdatedAt\x18\xf5\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"d\n" +
	"\fTagProperty1\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\atagObjs\x18\x03 \x03(\v2\x0e.listah.v1.TagR\atagObjs\"\x98\x01\n" +
	"\x0fInnerPropTagMap\x12;\n" +
	"\x05value\x18\x01 \x03(\v2%.listah.v1.InnerPropTagMap.ValueEntryR\x05value\x1aH\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.listah.v1.TagR\x05value:\x028\x01\"0\n" +
	"\x06MapObj\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\"\x9d\x01\n" +
	"\x0eTagPropertyMap\x12:\n" +
	"\x05value\x18\x01 \x03(\v2$.listah.v1.TagPropertyMap.ValueEntryR\x05value\x1aO\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.listah.v1.StringListR\x05value:\x028\x01\"\xa9\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x120\n" +
	"\x05props\x18\x06 \x03(\v2\x1a.listah.v1.Item.PropsEntryR\x05props\x12\x1e\n" +
	"\n" +
	"softDelete\x18\a \x01(\bR\n" +
	"softDelete\x12(\n" +
	"\atagObjs\x18\b \x03(\v2\x0e.listah.v1.TagR\atagObjs\x12-\n" +
	"\bpropObjs\x18\t \x03(\v2\x11.listah.v1.MapObjR\bpropObjs\x12\x1d\n" +
	"\tupdatedBy\x18\xf4\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\tupdatedAt\x18\xf5\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x06Filter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"softDelete\x18\a \x01(\bR\n" +
	"softDelete\x12\x1d\n" +
	"\tupdatedBy\x18\xf4\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\tupdatedAt\x18\xf5\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"J\n" +
	"\x06Search\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x03 \x03(\tR\afilters\"`\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x03R\x06volume\"K\n" +
	"\tReadQuery\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\\\n" +
	"\rReadReference\x12 \n" +
	"\x03tag\x18\x01 \x01(\v2\x0e.listah.v1.TagR\x03tag\x12)\n" +
	"\x06filter\x18\x02 \x01(\v2\x11.listah.v1.FilterR\x06filter\"\xc2\x01\n" +
	"\vReadRequest\x12+\n" +
	"\x05query\x18\xf4\x03 \x01(\v2\x14.listah.v1.ReadQueryR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf5\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\x127\n" +
	"\treference\x18\xf6\x03 \x01(\v2\x18.listah.v1.ReadReferenceR\treference\x12\x15\n" +
	"\x05title\x18\xf7\x03 \x01(\tR\x05title*v\n" +
	"\x10AuditUpdaterEnum\x12\"\n" +
	"\x1eAUDIT_UPDATER_ENUM_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAUDIT_UPDATER_ENUM_FRONTEND\x10\x01\x12\x1d\n" +
	"\x19AUDIT_UPDATER_ENUM_SYSOPS\x10\x02B)Z'cornucopia/listah/internal/pkg/proto/v1b\x06proto3"

var (
	file_v1_commons_proto_rawDescOnce sync.Once
	file_v1_commons_proto_rawDescData []byte
)

func file_v1_commons_proto_rawDescGZIP() []byte {
	file_v1_commons_proto_rawDescOnce.Do(func() {
		file_v1_commons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_commons_proto_rawDesc), len(file_v1_commons_proto_rawDesc)))
	})
	return file_v1_commons_proto_rawDescData
}

var file_v1_commons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_commons_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_commons_proto_goTypes = []any{
	(AuditUpdaterEnum)(0),         // 0: listah.v1.AuditUpdaterEnum
	(*Tag)(nil),                   // 1: listah.v1.Tag
	(*TagProperty1)(nil),          // 2: listah.v1.TagProperty1
	(*InnerPropTagMap)(nil),       // 3: listah.v1.InnerPropTagMap
	(*MapObj)(nil),                // 4: listah.v1.MapObj
	(*StringList)(nil),            // 5: listah.v1.StringList
	(*TagPropertyMap)(nil),        // 6: listah.v1.TagPropertyMap
	(*Item)(nil),                  // 7: listah.v1.Item
	(*Filter)(nil),                // 8: listah.v1.Filter
	(*Search)(nil),                // 9: listah.v1.Search
	(*Pagination)(nil),            // 10: listah.v1.Pagination
	(*ReadQuery)(nil),             // 11: listah.v1.ReadQuery
	(*ReadReference)(nil),         // 12: listah.v1.ReadReference
	(*ReadRequest)(nil),           // 13: listah.v1.ReadRequest
	nil,                           // 14: listah.v1.InnerPropTagMap.ValueEntry
	nil,                           // 15: listah.v1.TagPropertyMap.ValueEntry
	nil,                           // 16: listah.v1.Item.PropsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_v1_commons_proto_depIdxs = []int32{
	17, // 0: listah.v1.Tag.updatedAt:type_name -> google.protobuf.Timestamp
	1,  // 1: listah.v1.TagProperty1.tagObjs:type_name -> listah.v1.Tag
	14, // 2: listah.v1.InnerPropTagMap.value:type_name -> listah.v1.InnerPropTagMap.ValueEntry
	15, // 3: listah.v1.TagPropertyMap.value:type_name -> listah.v1.TagPropertyMap.ValueEntry
	16, // 4: listah.v1.Item.props:type_name -> listah.v1.Item.PropsEntry
	1,  // 5: listah.v1.Item.tagObjs:type_name -> listah.v1.Tag
	4,  // 6: listah.v1.Item.propObjs:type_name -> listah.v1.MapObj
	17, // 7: listah.v1.Item.updatedAt:type_name -> google.protobuf.Timestamp
	17, // 8: listah.v1.Filter.updatedAt:type_name -> google.protobuf.Timestamp
	1,  // 9: listah.v1.ReadReference.tag:type_name -> listah.v1.Tag
	8,  // 10: listah.v1.ReadReference.filter:type_name -> listah.v1.Filter
	11, // 11: listah.v1.ReadRequest.query:type_name -> listah.v1.ReadQuery
	10, // 12: listah.v1.ReadRequest.pagination:type_name -> listah.v1.Pagination
	12, // 13: listah.v1.ReadRequest.reference:type_name -> listah.v1.ReadReference
	1,  // 14: listah.v1.InnerPropTagMap.ValueEntry.value:type_name -> listah.v1.Tag
	5,  // 15: listah.v1.TagPropertyMap.ValueEntry.value:type_name -> listah.v1.StringList
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_v1_commons_proto_init() }
func file_v1_commons_proto_init() {
	if File_v1_commons_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_commons_proto_rawDesc), len(file_v1_commons_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_commons_proto_goTypes,
		DependencyIndexes: file_v1_commons_proto_depIdxs,
		EnumInfos:         file_v1_commons_proto_enumTypes,
		MessageInfos:      file_v1_commons_proto_msgTypes,
	}.Build()
	File_v1_commons_proto = out.File
	file_v1_commons_proto_goTypes = nil
	file_v1_commons_proto_depIdxs = nil
}
