// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Machine-readable error codes for the frontend to switch on
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED  ErrorCode = 0
	ErrorCode_VALIDATION_FAILED       ErrorCode = 1
	ErrorCode_ALREADY_EXISTS          ErrorCode = 2
	ErrorCode_NOT_FOUND               ErrorCode = 3
	ErrorCode_INTERNAL_DATABASE_ERROR ErrorCode = 4 // Masked on the frontend as a generic 500
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "VALIDATION_FAILED",
		2: "ALREADY_EXISTS",
		3: "NOT_FOUND",
		4: "INTERNAL_DATABASE_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":  0,
		"VALIDATION_FAILED":       1,
		"ALREADY_EXISTS":          2,
		"NOT_FOUND":               3,
		"INTERNAL_DATABASE_ERROR": 4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_errors_proto_rawDescGZIP(), []int{0}
}

// Custom detail for form validation or constraint violations
type FieldViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`             // e.g., "email"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // e.g., "This email is already registered."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The core payload we will attach to the error status
type BadRequestDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=listah.v1.ErrorCode" json:"code,omitempty"`
	FieldViolations []*FieldViolation      `protobuf:"bytes,2,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BadRequestDetails) Reset() {
	*x = BadRequestDetails{}
	mi := &file_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequestDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequestDetails) ProtoMessage() {}

func (x *BadRequestDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequestDetails.ProtoReflect.Descriptor instead.
func (*BadRequestDetails) Descriptor() ([]byte, []int) {
	return file_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *BadRequestDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *BadRequestDetails) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

// For generic or system-wide errors
type SystemErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=listah.v1.ErrorCode" json:"code,omitempty"`
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"` // A UUID to map frontend errors to backend server logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemErrorDetails) Reset() {
	*x = SystemErrorDetails{}
	mi := &file_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemErrorDetails) ProtoMessage() {}

func (x *SystemErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemErrorDetails.ProtoReflect.Descriptor instead.
func (*SystemErrorDetails) Descriptor() ([]byte, []int) {
	return file_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *SystemErrorDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *SystemErrorDetails) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

var File_v1_errors_proto protoreflect.FileDescriptor

const file_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/errors.proto\x12\tlistah.v1\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x83\x01\n" +
	"\x11BadRequestDetails\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.listah.v1.ErrorCodeR\x04code\x12D\n" +
	"\x10field_violations\x18\x02 \x03(\v2\x19.listah.v1.FieldViolationR\x0ffieldViolations\"_\n" +
	"\x12SystemErrorDetails\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.listah.v1.ErrorCodeR\x04code\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId*~\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VALIDATION_FAILED\x10\x01\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\x1b\n" +
	"\x17INTERNAL_DATABASE_ERROR\x10\x04B)Z'cornucopia/listah/internal/pkg/proto/v1b\x06proto3"

var (
	file_v1_errors_proto_rawDescOnce sync.Once
	file_v1_errors_proto_rawDescData []byte
)

func file_v1_errors_proto_rawDescGZIP() []byte {
	file_v1_errors_proto_rawDescOnce.Do(func() {
		file_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_errors_proto_rawDesc), len(file_v1_errors_proto_rawDesc)))
	})
	return file_v1_errors_proto_rawDescData
}

var file_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: listah.v1.ErrorCode
	(*FieldViolation)(nil),     // 1: listah.v1.FieldViolation
	(*BadRequestDetails)(nil),  // 2: listah.v1.BadRequestDetails
	(*SystemErrorDetails)(nil), // 3: listah.v1.SystemErrorDetails
}
var file_v1_errors_proto_depIdxs = []int32{
	0, // 0: listah.v1.BadRequestDetails.code:type_name -> listah.v1.ErrorCode
	1, // 1: listah.v1.BadRequestDetails.field_violations:type_name -> listah.v1.FieldViolation
	0, // 2: listah.v1.SystemErrorDetails.code:type_name -> listah.v1.ErrorCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_errors_proto_init() }
func file_v1_errors_proto_init() {
	if File_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_errors_proto_rawDesc), len(file_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_errors_proto_goTypes,
		DependencyIndexes: file_v1_errors_proto_depIdxs,
		EnumInfos:         file_v1_errors_proto_enumTypes,
		MessageInfos:      file_v1_errors_proto_msgTypes,
	}.Build()
	File_v1_errors_proto = out.File
	file_v1_errors_proto_goTypes = nil
	file_v1_errors_proto_depIdxs = nil
}
