// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/item.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item Messages
type ItemServiceCreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceCreateItemRequest) Reset() {
	*x = ItemServiceCreateItemRequest{}
	mi := &file_v1_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceCreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceCreateItemRequest) ProtoMessage() {}

func (x *ItemServiceCreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceCreateItemRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceCreateItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemServiceCreateItemRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemServiceCreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=itemIds,proto3" json:"itemIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceCreateItemResponse) Reset() {
	*x = ItemServiceCreateItemResponse{}
	mi := &file_v1_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceCreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceCreateItemResponse) ProtoMessage() {}

func (x *ItemServiceCreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceCreateItemResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceCreateItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemServiceCreateItemResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type ItemServiceReadItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadItemRequest) Reset() {
	*x = ItemServiceReadItemRequest{}
	mi := &file_v1_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadItemRequest) ProtoMessage() {}

func (x *ItemServiceReadItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadItemRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemServiceReadItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadItemRequest) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadItemRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadItemResponse) Reset() {
	*x = ItemServiceReadItemResponse{}
	mi := &file_v1_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadItemResponse) ProtoMessage() {}

func (x *ItemServiceReadItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadItemResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemServiceReadItemResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemServiceReadItemResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadItemResponse) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadItemResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertItemRequest) Reset() {
	*x = ItemServiceUpsertItemRequest{}
	mi := &file_v1_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertItemRequest) ProtoMessage() {}

func (x *ItemServiceUpsertItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertItemRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{4}
}

func (x *ItemServiceUpsertItemRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemServiceUpsertItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=itemIds,proto3" json:"itemIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertItemResponse) Reset() {
	*x = ItemServiceUpsertItemResponse{}
	mi := &file_v1_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertItemResponse) ProtoMessage() {}

func (x *ItemServiceUpsertItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertItemResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{5}
}

func (x *ItemServiceUpsertItemResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

// Tag Messages
type ItemServiceReadTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadTagRequest) Reset() {
	*x = ItemServiceReadTagRequest{}
	mi := &file_v1_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagRequest) ProtoMessage() {}

func (x *ItemServiceReadTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{6}
}

func (x *ItemServiceReadTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadTagRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Item                `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadTagResponse) Reset() {
	*x = ItemServiceReadTagResponse{}
	mi := &file_v1_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagResponse) ProtoMessage() {}

func (x *ItemServiceReadTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{7}
}

func (x *ItemServiceReadTagResponse) GetTags() []*Item {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemServiceReadTagResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Item                `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertTagRequest) Reset() {
	*x = ItemServiceUpsertTagRequest{}
	mi := &file_v1_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertTagRequest) ProtoMessage() {}

func (x *ItemServiceUpsertTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertTagRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{8}
}

func (x *ItemServiceUpsertTagRequest) GetTags() []*Item {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ItemServiceUpsertTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagIds        []string               `protobuf:"bytes,1,rep,name=tagIds,proto3" json:"tagIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertTagResponse) Reset() {
	*x = ItemServiceUpsertTagResponse{}
	mi := &file_v1_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertTagResponse) ProtoMessage() {}

func (x *ItemServiceUpsertTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertTagResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertTagResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{9}
}

func (x *ItemServiceUpsertTagResponse) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

// Filter Messages
type ItemServiceReadFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadFilterRequest) Reset() {
	*x = ItemServiceReadFilterRequest{}
	mi := &file_v1_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadFilterRequest) ProtoMessage() {}

func (x *ItemServiceReadFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadFilterRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadFilterRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{10}
}

func (x *ItemServiceReadFilterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadFilterRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Item                `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadFilterResponse) Reset() {
	*x = ItemServiceReadFilterResponse{}
	mi := &file_v1_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadFilterResponse) ProtoMessage() {}

func (x *ItemServiceReadFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadFilterResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadFilterResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{11}
}

func (x *ItemServiceReadFilterResponse) GetTags() []*Item {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemServiceReadFilterResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Item                `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertFilterRequest) Reset() {
	*x = ItemServiceUpsertFilterRequest{}
	mi := &file_v1_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertFilterRequest) ProtoMessage() {}

func (x *ItemServiceUpsertFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertFilterRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertFilterRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{12}
}

func (x *ItemServiceUpsertFilterRequest) GetTags() []*Item {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ItemServiceUpsertFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagIds        []string               `protobuf:"bytes,1,rep,name=tagIds,proto3" json:"tagIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertFilterResponse) Reset() {
	*x = ItemServiceUpsertFilterResponse{}
	mi := &file_v1_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertFilterResponse) ProtoMessage() {}

func (x *ItemServiceUpsertFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertFilterResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertFilterResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{13}
}

func (x *ItemServiceUpsertFilterResponse) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

var File_v1_item_proto protoreflect.FileDescriptor

const file_v1_item_proto_rawDesc = "" +
	"\n" +
	"\rv1/item.proto\x12\tlistah.v1\x1a\x10v1/commons.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$gnostic/openapi/v3/annotations.proto\"E\n" +
	"\x1cItemServiceCreateItemRequest\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x05items\"9\n" +
	"\x1dItemServiceCreateItemResponse\x12\x18\n" +
	"\aitemIds\x18\x01 \x03(\tR\aitemIds\"\x97\x01\n" +
	"\x1aItemServiceReadItemRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"\xbf\x01\n" +
	"\x1bItemServiceReadItemResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x05items\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"E\n" +
	"\x1cItemServiceUpsertItemRequest\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x05items\"9\n" +
	"\x1dItemServiceUpsertItemResponse\x12\x18\n" +
	"\aitemIds\x18\x01 \x03(\tR\aitemIds\"l\n" +
	"\x19ItemServiceReadTagRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"y\n" +
	"\x1aItemServiceReadTagResponse\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x04tags\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"B\n" +
	"\x1bItemServiceUpsertTagRequest\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x04tags\"6\n" +
	"\x1cItemServiceUpsertTagResponse\x12\x16\n" +
	"\x06tagIds\x18\x01 \x03(\tR\x06tagIds\"o\n" +
	"\x1cItemServiceReadFilterRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"|\n" +
	"\x1dItemServiceReadFilterResponse\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x04tags\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"E\n" +
	"\x1eItemServiceUpsertFilterRequest\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x04tags\"9\n" +
	"\x1fItemServiceUpsertFilterResponse\x12\x16\n" +
	"\x06tagIds\x18\x01 \x03(\tR\x06tagIds2\xab\x06\n" +
	"\vItemService\x12q\n" +
	"\n" +
	"CreateItem\x12'.listah.v1.ItemServiceCreateItemRequest\x1a(.listah.v1.ItemServiceCreateItemResponse\"\x10\xbaG\r\x1a\vCreate Item\x12l\n" +
	"\bReadItem\x12%.listah.v1.ItemServiceReadItemRequest\x1a&.listah.v1.ItemServiceReadItemResponse\"\x11\xbaG\v\x1a\tRead Item\x90\x02\x01\x12q\n" +
	"\n" +
	"UpsertItem\x12'.listah.v1.ItemServiceUpsertItemRequest\x1a(.listah.v1.ItemServiceUpsertItemResponse\"\x10\xbaG\r\x1a\vUpsert Item\x12h\n" +
	"\aReadTag\x12$.listah.v1.ItemServiceReadTagRequest\x1a%.listah.v1.ItemServiceReadTagResponse\"\x10\xbaG\n" +
	"\x1a\bRead Tag\x90\x02\x01\x12m\n" +
	"\tUpsertTag\x12&.listah.v1.ItemServiceUpsertTagRequest\x1a'.listah.v1.ItemServiceUpsertTagResponse\"\x0f\xbaG\f\x1a\n" +
	"Upsert Tag\x12t\n" +
	"\n" +
	"ReadFilter\x12'.listah.v1.ItemServiceReadFilterRequest\x1a(.listah.v1.ItemServiceReadFilterResponse\"\x13\xbaG\r\x1a\vRead Filter\x90\x02\x01\x12y\n" +
	"\fUpsertFilter\x12).listah.v1.ItemServiceUpsertFilterRequest\x1a*.listah.v1.ItemServiceUpsertFilterResponse\"\x12\xbaG\x0f\x1a\rUpsert FilterB)Z'cornucopia/listah/internal/pkg/proto/v1b\x06proto3"

var (
	file_v1_item_proto_rawDescOnce sync.Once
	file_v1_item_proto_rawDescData []byte
)

func file_v1_item_proto_rawDescGZIP() []byte {
	file_v1_item_proto_rawDescOnce.Do(func() {
		file_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_item_proto_rawDesc), len(file_v1_item_proto_rawDesc)))
	})
	return file_v1_item_proto_rawDescData
}

var file_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_item_proto_goTypes = []any{
	(*ItemServiceCreateItemRequest)(nil),    // 0: listah.v1.ItemServiceCreateItemRequest
	(*ItemServiceCreateItemResponse)(nil),   // 1: listah.v1.ItemServiceCreateItemResponse
	(*ItemServiceReadItemRequest)(nil),      // 2: listah.v1.ItemServiceReadItemRequest
	(*ItemServiceReadItemResponse)(nil),     // 3: listah.v1.ItemServiceReadItemResponse
	(*ItemServiceUpsertItemRequest)(nil),    // 4: listah.v1.ItemServiceUpsertItemRequest
	(*ItemServiceUpsertItemResponse)(nil),   // 5: listah.v1.ItemServiceUpsertItemResponse
	(*ItemServiceReadTagRequest)(nil),       // 6: listah.v1.ItemServiceReadTagRequest
	(*ItemServiceReadTagResponse)(nil),      // 7: listah.v1.ItemServiceReadTagResponse
	(*ItemServiceUpsertTagRequest)(nil),     // 8: listah.v1.ItemServiceUpsertTagRequest
	(*ItemServiceUpsertTagResponse)(nil),    // 9: listah.v1.ItemServiceUpsertTagResponse
	(*ItemServiceReadFilterRequest)(nil),    // 10: listah.v1.ItemServiceReadFilterRequest
	(*ItemServiceReadFilterResponse)(nil),   // 11: listah.v1.ItemServiceReadFilterResponse
	(*ItemServiceUpsertFilterRequest)(nil),  // 12: listah.v1.ItemServiceUpsertFilterRequest
	(*ItemServiceUpsertFilterResponse)(nil), // 13: listah.v1.ItemServiceUpsertFilterResponse
	(*Item)(nil),                            // 14: listah.v1.Item
	(*Search)(nil),                          // 15: listah.v1.Search
	(*Pagination)(nil),                      // 16: listah.v1.Pagination
}
var file_v1_item_proto_depIdxs = []int32{
	14, // 0: listah.v1.ItemServiceCreateItemRequest.items:type_name -> listah.v1.Item
	15, // 1: listah.v1.ItemServiceReadItemRequest.query:type_name -> listah.v1.Search
	16, // 2: listah.v1.ItemServiceReadItemRequest.pagination:type_name -> listah.v1.Pagination
	14, // 3: listah.v1.ItemServiceReadItemResponse.items:type_name -> listah.v1.Item
	15, // 4: listah.v1.ItemServiceReadItemResponse.query:type_name -> listah.v1.Search
	16, // 5: listah.v1.ItemServiceReadItemResponse.pagination:type_name -> listah.v1.Pagination
	14, // 6: listah.v1.ItemServiceUpsertItemRequest.items:type_name -> listah.v1.Item
	16, // 7: listah.v1.ItemServiceReadTagRequest.pagination:type_name -> listah.v1.Pagination
	14, // 8: listah.v1.ItemServiceReadTagResponse.tags:type_name -> listah.v1.Item
	16, // 9: listah.v1.ItemServiceReadTagResponse.pagination:type_name -> listah.v1.Pagination
	14, // 10: listah.v1.ItemServiceUpsertTagRequest.tags:type_name -> listah.v1.Item
	16, // 11: listah.v1.ItemServiceReadFilterRequest.pagination:type_name -> listah.v1.Pagination
	14, // 12: listah.v1.ItemServiceReadFilterResponse.tags:type_name -> listah.v1.Item
	16, // 13: listah.v1.ItemServiceReadFilterResponse.pagination:type_name -> listah.v1.Pagination
	14, // 14: listah.v1.ItemServiceUpsertFilterRequest.tags:type_name -> listah.v1.Item
	0,  // 15: listah.v1.ItemService.CreateItem:input_type -> listah.v1.ItemServiceCreateItemRequest
	2,  // 16: listah.v1.ItemService.ReadItem:input_type -> listah.v1.ItemServiceReadItemRequest
	4,  // 17: listah.v1.ItemService.UpsertItem:input_type -> listah.v1.ItemServiceUpsertItemRequest
	6,  // 18: listah.v1.ItemService.ReadTag:input_type -> listah.v1.ItemServiceReadTagRequest
	8,  // 19: listah.v1.ItemService.UpsertTag:input_type -> listah.v1.ItemServiceUpsertTagRequest
	10, // 20: listah.v1.ItemService.ReadFilter:input_type -> listah.v1.ItemServiceReadFilterRequest
	12, // 21: listah.v1.ItemService.UpsertFilter:input_type -> listah.v1.ItemServiceUpsertFilterRequest
	1,  // 22: listah.v1.ItemService.CreateItem:output_type -> listah.v1.ItemServiceCreateItemResponse
	3,  // 23: listah.v1.ItemService.ReadItem:output_type -> listah.v1.ItemServiceReadItemResponse
	5,  // 24: listah.v1.ItemService.UpsertItem:output_type -> listah.v1.ItemServiceUpsertItemResponse
	7,  // 25: listah.v1.ItemService.ReadTag:output_type -> listah.v1.ItemServiceReadTagResponse
	9,  // 26: listah.v1.ItemService.UpsertTag:output_type -> listah.v1.ItemServiceUpsertTagResponse
	11, // 27: listah.v1.ItemService.ReadFilter:output_type -> listah.v1.ItemServiceReadFilterResponse
	13, // 28: listah.v1.ItemService.UpsertFilter:output_type -> listah.v1.ItemServiceUpsertFilterResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_item_proto_init() }
func file_v1_item_proto_init() {
	if File_v1_item_proto != nil {
		return
	}
	file_v1_commons_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_item_proto_rawDesc), len(file_v1_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_item_proto_goTypes,
		DependencyIndexes: file_v1_item_proto_depIdxs,
		MessageInfos:      file_v1_item_proto_msgTypes,
	}.Build()
	File_v1_item_proto = out.File
	file_v1_item_proto_goTypes = nil
	file_v1_item_proto_depIdxs = nil
}
