// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/item.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemService_ReadItem_FullMethodName     = "/listah.v1.ItemService/ReadItem"
	ItemService_ReadCategory_FullMethodName = "/listah.v1.ItemService/ReadCategory"
	ItemService_Upsert_FullMethodName       = "/listah.v1.ItemService/Upsert"
)

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemServiceClient interface {
	ReadItem(ctx context.Context, in *ItemServiceReadItemRequest, opts ...grpc.CallOption) (*ItemServiceReadItemResponse, error)
	ReadCategory(ctx context.Context, in *ItemServiceReadCategoryRequest, opts ...grpc.CallOption) (*ItemServiceReadCategoryResponse, error)
	Upsert(ctx context.Context, in *ItemServiceUpsertRequest, opts ...grpc.CallOption) (*ItemServiceUpsertResponse, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) ReadItem(ctx context.Context, in *ItemServiceReadItemRequest, opts ...grpc.CallOption) (*ItemServiceReadItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemServiceReadItemResponse)
	err := c.cc.Invoke(ctx, ItemService_ReadItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ReadCategory(ctx context.Context, in *ItemServiceReadCategoryRequest, opts ...grpc.CallOption) (*ItemServiceReadCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemServiceReadCategoryResponse)
	err := c.cc.Invoke(ctx, ItemService_ReadCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Upsert(ctx context.Context, in *ItemServiceUpsertRequest, opts ...grpc.CallOption) (*ItemServiceUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemServiceUpsertResponse)
	err := c.cc.Invoke(ctx, ItemService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
// All implementations should embed UnimplementedItemServiceServer
// for forward compatibility.
type ItemServiceServer interface {
	ReadItem(context.Context, *ItemServiceReadItemRequest) (*ItemServiceReadItemResponse, error)
	ReadCategory(context.Context, *ItemServiceReadCategoryRequest) (*ItemServiceReadCategoryResponse, error)
	Upsert(context.Context, *ItemServiceUpsertRequest) (*ItemServiceUpsertResponse, error)
}

// UnimplementedItemServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemServiceServer struct{}

func (UnimplementedItemServiceServer) ReadItem(context.Context, *ItemServiceReadItemRequest) (*ItemServiceReadItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadItem not implemented")
}
func (UnimplementedItemServiceServer) ReadCategory(context.Context, *ItemServiceReadCategoryRequest) (*ItemServiceReadCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCategory not implemented")
}
func (UnimplementedItemServiceServer) Upsert(context.Context, *ItemServiceUpsertRequest) (*ItemServiceUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedItemServiceServer) testEmbeddedByValue() {}

// UnsafeItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServiceServer will
// result in compilation errors.
type UnsafeItemServiceServer interface {
	mustEmbedUnimplementedItemServiceServer()
}

func RegisterItemServiceServer(s grpc.ServiceRegistrar, srv ItemServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemService_ServiceDesc, srv)
}

func _ItemService_ReadItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemServiceReadItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ReadItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ReadItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ReadItem(ctx, req.(*ItemServiceReadItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ReadCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemServiceReadCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ReadCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ReadCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ReadCategory(ctx, req.(*ItemServiceReadCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemServiceUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Upsert(ctx, req.(*ItemServiceUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemService_ServiceDesc is the grpc.ServiceDesc for ItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listah.v1.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadItem",
			Handler:    _ItemService_ReadItem_Handler,
		},
		{
			MethodName: "ReadCategory",
			Handler:    _ItemService_ReadCategory_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _ItemService_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/item.proto",
}
