# Use root/example as user/password credentials
services:

  mongo:
    image: mongo
    restart: always
    environment:
      ENV: local
    env_file: .env
    volumes:
       - ./db_data/mongodb/:/var/lib/mongodb/
    ports:
      - "27017:27017"
