bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
loglevel warning


# Persistence
save 900 1
save 300 10
save 60 10000
dir /data
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec



# Security: disable default user and create an ACL user
user default off
user safe_redis_user on >Super123Safe456Password789! ~listah:sessions:* ~listah:users:* ~listah:items:* +@read +@write -@admin
user admin_redis_user on >SuperAdmin123Safe456Password789! ~* +@all
