/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as ItemsRouteRouteImport } from './routes/items/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'

const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRouteRoute = ItemsRouteRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRouteRoute,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/items/': typeof ItemsIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/items/': typeof ItemsIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/sign-up' | '/items/' | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items' | '/sign-up'
  id: '__root__' | '/' | '/items' | '/sign-up' | '/items/' | '/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRouteRoute: typeof ItemsRouteRouteWithChildren
  SignUpRouteRoute: typeof SignUpRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRouteRoute
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRouteRoute
    }
  }
}

interface ItemsRouteRouteChildren {
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteRouteChildren: ItemsRouteRouteChildren = {
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteRouteWithChildren = ItemsRouteRoute._addFileChildren(
  ItemsRouteRouteChildren,
)

interface SignUpRouteRouteChildren {
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteRouteChildren: SignUpRouteRouteChildren = {
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteRouteWithChildren = SignUpRouteRoute._addFileChildren(
  SignUpRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRouteRoute: ItemsRouteRouteWithChildren,
  SignUpRouteRoute: SignUpRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
