/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsItemItemIdRouteImport } from './routes/items/item-$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemItemIdRoute = ItemsItemItemIdRouteImport.update({
  id: '/items/item-$itemId',
  path: '/items/item-$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items/item-$itemId': typeof ItemsItemItemIdRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items/item-$itemId': typeof ItemsItemItemIdRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items/item-$itemId': typeof ItemsItemItemIdRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items/item-$itemId' | '/items'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items/item-$itemId' | '/items'
  id: '__root__' | '/' | '/items/item-$itemId' | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsItemItemIdRoute: typeof ItemsItemItemIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/item-$itemId': {
      id: '/items/item-$itemId'
      path: '/items/item-$itemId'
      fullPath: '/items/item-$itemId'
      preLoaderRoute: typeof ItemsItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsItemItemIdRoute: ItemsItemItemIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
