services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./local/db_data:/var/lib/postgresql/
    env_file: ../../.env
    environment:
      ENV: local
    ports:
      - "5434:5432"

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:latest
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ../liquibase/changelog/:/liquibase/changelog/
    environment:
      LIQUIBASE_COMMAND_URL: ${LIQUID_BASE_CONNECTION_URL}
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.yaml
      LIQUIBASE_LOG_LEVEL: INFO
    command: update

networks:
  default:
    driver: bridge
