
services:


  # OpenTelemetry Collector
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger
      - zipkin
      - prometheus


  # Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686" # UI
      - "4317:4317" # Jaeger gRPC
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411" # Zipkin UI and API

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

networks:
  default:
    driver: bridge
