
services:
  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin-all-in-one
      - prometheus
      - jaeger

  # Premetheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.5.0
    restart: always
    ports:
      - 16686:16686
      - 14268:14268
      # - 4317:4317
      # - 4318:4318
      # - 5778:5778
      # - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
