receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
processors:
extensions:
  health_check: {}
exporters:
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true
  otlphttp:
    endpoint: "localhost:4318"
    tls:
      insecure: true
  prometheus:
    endpoint: "localhost:9090"
    namespace: testapp
  debug:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, otlphttp, debug]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
