
global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s


scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:9090']
