
global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s


scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['listah-otel-collector:8889'] # OpenTelemetry Collector metrics endpoint
  - job_name: 'listah-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:8080'] # Listah API metrics endpoint
  - job_name: 'listah-web-next'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:5050'] # Listah Web Next metrics endpoint
  - job_name: 'listah-web-rr'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:5173'] # Listah Web RR metrics endpoint
