
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile_api    
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./apps/api
          target: /app/apps/api        
        - action: rebuild
          path: ./internal
          target: /app/internal