
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4317 
      - 6831:6831/udp 
      - 16686:16686 
      - 14268:14268 
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4318:4318
      - 55679:55679
    depends_on:
      - jaeger