// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/item.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item Messages
type ItemServiceReadItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadItemRequest) Reset() {
	*x = ItemServiceReadItemRequest{}
	mi := &file_v1_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadItemRequest) ProtoMessage() {}

func (x *ItemServiceReadItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadItemRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemServiceReadItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadItemRequest) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadItemRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadItemResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalRecordCount int32                  `protobuf:"varint,2,opt,name=totalRecordCount,proto3" json:"totalRecordCount,omitempty"`
	UserId           string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query            *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination       *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemServiceReadItemResponse) Reset() {
	*x = ItemServiceReadItemResponse{}
	mi := &file_v1_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadItemResponse) ProtoMessage() {}

func (x *ItemServiceReadItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadItemResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemServiceReadItemResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemServiceReadItemResponse) GetTotalRecordCount() int32 {
	if x != nil {
		return x.TotalRecordCount
	}
	return 0
}

func (x *ItemServiceReadItemResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadItemResponse) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadItemResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertItemRequest) Reset() {
	*x = ItemServiceUpsertItemRequest{}
	mi := &file_v1_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertItemRequest) ProtoMessage() {}

func (x *ItemServiceUpsertItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertItemRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemServiceUpsertItemRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemServiceUpsertItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=itemIds,proto3" json:"itemIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertItemResponse) Reset() {
	*x = ItemServiceUpsertItemResponse{}
	mi := &file_v1_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertItemResponse) ProtoMessage() {}

func (x *ItemServiceUpsertItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertItemResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemServiceUpsertItemResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

// Tag Messages
type ItemServiceReadTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadTagRequest) Reset() {
	*x = ItemServiceReadTagRequest{}
	mi := &file_v1_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagRequest) ProtoMessage() {}

func (x *ItemServiceReadTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{4}
}

func (x *ItemServiceReadTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadTagRequest) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadTagRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadTagResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tags             []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	TotalRecordCount int32                  `protobuf:"varint,2,opt,name=totalRecordCount,proto3" json:"totalRecordCount,omitempty"`
	TagidPropMap     map[string]*StringList `protobuf:"bytes,3,rep,name=tagidPropMap,proto3" json:"tagidPropMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserId           string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query            *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination       *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemServiceReadTagResponse) Reset() {
	*x = ItemServiceReadTagResponse{}
	mi := &file_v1_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagResponse) ProtoMessage() {}

func (x *ItemServiceReadTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{5}
}

func (x *ItemServiceReadTagResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemServiceReadTagResponse) GetTotalRecordCount() int32 {
	if x != nil {
		return x.TotalRecordCount
	}
	return 0
}

func (x *ItemServiceReadTagResponse) GetTagidPropMap() map[string]*StringList {
	if x != nil {
		return x.TagidPropMap
	}
	return nil
}

func (x *ItemServiceReadTagResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadTagResponse) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadTagResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertTagRequest) Reset() {
	*x = ItemServiceUpsertTagRequest{}
	mi := &file_v1_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertTagRequest) ProtoMessage() {}

func (x *ItemServiceUpsertTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertTagRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{6}
}

func (x *ItemServiceUpsertTagRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ItemServiceUpsertTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagIds        []string               `protobuf:"bytes,1,rep,name=tagIds,proto3" json:"tagIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertTagResponse) Reset() {
	*x = ItemServiceUpsertTagResponse{}
	mi := &file_v1_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertTagResponse) ProtoMessage() {}

func (x *ItemServiceUpsertTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertTagResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertTagResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{7}
}

func (x *ItemServiceUpsertTagResponse) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

// Tag Property Messages
type ItemServiceReadTagPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadTagPropertyRequest) Reset() {
	*x = ItemServiceReadTagPropertyRequest{}
	mi := &file_v1_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagPropertyRequest) ProtoMessage() {}

func (x *ItemServiceReadTagPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagPropertyRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagPropertyRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{8}
}

func (x *ItemServiceReadTagPropertyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadTagPropertyRequest) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadTagPropertyRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadTagPropertyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Props            map[string]*StringList `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalRecordCount int32                  `protobuf:"varint,2,opt,name=totalRecordCount,proto3" json:"totalRecordCount,omitempty"`
	UserId           string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query            *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination       *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemServiceReadTagPropertyResponse) Reset() {
	*x = ItemServiceReadTagPropertyResponse{}
	mi := &file_v1_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadTagPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadTagPropertyResponse) ProtoMessage() {}

func (x *ItemServiceReadTagPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadTagPropertyResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadTagPropertyResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{9}
}

func (x *ItemServiceReadTagPropertyResponse) GetProps() map[string]*StringList {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ItemServiceReadTagPropertyResponse) GetTotalRecordCount() int32 {
	if x != nil {
		return x.TotalRecordCount
	}
	return 0
}

func (x *ItemServiceReadTagPropertyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadTagPropertyResponse) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadTagPropertyResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Filter Messages
type ItemServiceReadFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query         *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceReadFilterRequest) Reset() {
	*x = ItemServiceReadFilterRequest{}
	mi := &file_v1_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadFilterRequest) ProtoMessage() {}

func (x *ItemServiceReadFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadFilterRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceReadFilterRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{10}
}

func (x *ItemServiceReadFilterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadFilterRequest) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadFilterRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceReadFilterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Filters          []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	TotalRecordCount int32                  `protobuf:"varint,2,opt,name=totalRecordCount,proto3" json:"totalRecordCount,omitempty"`
	UserId           string                 `protobuf:"bytes,500,opt,name=userId,proto3" json:"userId,omitempty"`
	Query            *Search                `protobuf:"bytes,501,opt,name=query,proto3" json:"query,omitempty"`
	Pagination       *Pagination            `protobuf:"bytes,502,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemServiceReadFilterResponse) Reset() {
	*x = ItemServiceReadFilterResponse{}
	mi := &file_v1_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceReadFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceReadFilterResponse) ProtoMessage() {}

func (x *ItemServiceReadFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceReadFilterResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceReadFilterResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{11}
}

func (x *ItemServiceReadFilterResponse) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ItemServiceReadFilterResponse) GetTotalRecordCount() int32 {
	if x != nil {
		return x.TotalRecordCount
	}
	return 0
}

func (x *ItemServiceReadFilterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ItemServiceReadFilterResponse) GetQuery() *Search {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ItemServiceReadFilterResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ItemServiceUpsertFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertFilterRequest) Reset() {
	*x = ItemServiceUpsertFilterRequest{}
	mi := &file_v1_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertFilterRequest) ProtoMessage() {}

func (x *ItemServiceUpsertFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertFilterRequest.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertFilterRequest) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{12}
}

func (x *ItemServiceUpsertFilterRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ItemServiceUpsertFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterIds     []string               `protobuf:"bytes,1,rep,name=filterIds,proto3" json:"filterIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemServiceUpsertFilterResponse) Reset() {
	*x = ItemServiceUpsertFilterResponse{}
	mi := &file_v1_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemServiceUpsertFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemServiceUpsertFilterResponse) ProtoMessage() {}

func (x *ItemServiceUpsertFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemServiceUpsertFilterResponse.ProtoReflect.Descriptor instead.
func (*ItemServiceUpsertFilterResponse) Descriptor() ([]byte, []int) {
	return file_v1_item_proto_rawDescGZIP(), []int{13}
}

func (x *ItemServiceUpsertFilterResponse) GetFilterIds() []string {
	if x != nil {
		return x.FilterIds
	}
	return nil
}

var File_v1_item_proto protoreflect.FileDescriptor

const file_v1_item_proto_rawDesc = "" +
	"\n" +
	"\rv1/item.proto\x12\tlistah.v1\x1a\x10v1/commons.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$gnostic/openapi/v3/annotations.proto\"\x97\x01\n" +
	"\x1aItemServiceReadItemRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"\xeb\x01\n" +
	"\x1bItemServiceReadItemResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x05items\x12*\n" +
	"\x10totalRecordCount\x18\x02 \x01(\x05R\x10totalRecordCount\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"E\n" +
	"\x1cItemServiceUpsertItemRequest\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.listah.v1.ItemR\x05items\"9\n" +
	"\x1dItemServiceUpsertItemResponse\x12\x18\n" +
	"\aitemIds\x18\x01 \x03(\tR\aitemIds\"\x96\x01\n" +
	"\x19ItemServiceReadTagRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"\x9c\x03\n" +
	"\x1aItemServiceReadTagResponse\x12\"\n" +
	"\x04tags\x18\x01 \x03(\v2\x0e.listah.v1.TagR\x04tags\x12*\n" +
	"\x10totalRecordCount\x18\x02 \x01(\x05R\x10totalRecordCount\x12[\n" +
	"\ftagidPropMap\x18\x03 \x03(\v27.listah.v1.ItemServiceReadTagResponse.TagidPropMapEntryR\ftagidPropMap\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\x1aV\n" +
	"\x11TagidPropMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.listah.v1.StringListR\x05value:\x028\x01\"A\n" +
	"\x1bItemServiceUpsertTagRequest\x12\"\n" +
	"\x04tags\x18\x01 \x03(\v2\x0e.listah.v1.TagR\x04tags\"6\n" +
	"\x1cItemServiceUpsertTagResponse\x12\x16\n" +
	"\x06tagIds\x18\x01 \x03(\tR\x06tagIds\"\x9e\x01\n" +
	"!ItemServiceReadTagPropertyRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"\xec\x02\n" +
	"\"ItemServiceReadTagPropertyResponse\x12N\n" +
	"\x05props\x18\x01 \x03(\v28.listah.v1.ItemServiceReadTagPropertyResponse.PropsEntryR\x05props\x12*\n" +
	"\x10totalRecordCount\x18\x02 \x01(\x05R\x10totalRecordCount\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\x1aO\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.listah.v1.StringListR\x05value:\x028\x01\"\x99\x01\n" +
	"\x1cItemServiceReadFilterRequest\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"\xf3\x01\n" +
	"\x1dItemServiceReadFilterResponse\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.listah.v1.FilterR\afilters\x12*\n" +
	"\x10totalRecordCount\x18\x02 \x01(\x05R\x10totalRecordCount\x12\x17\n" +
	"\x06userId\x18\xf4\x03 \x01(\tR\x06userId\x12(\n" +
	"\x05query\x18\xf5\x03 \x01(\v2\x11.listah.v1.SearchR\x05query\x126\n" +
	"\n" +
	"pagination\x18\xf6\x03 \x01(\v2\x15.listah.v1.PaginationR\n" +
	"pagination\"M\n" +
	"\x1eItemServiceUpsertFilterRequest\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.listah.v1.FilterR\afilters\"?\n" +
	"\x1fItemServiceUpsertFilterResponse\x12\x1c\n" +
	"\tfilterIds\x18\x01 \x03(\tR\tfilterIds2\xc4\x06\n" +
	"\vItemService\x12l\n" +
	"\bReadItem\x12%.listah.v1.ItemServiceReadItemRequest\x1a&.listah.v1.ItemServiceReadItemResponse\"\x11\xbaG\v\x1a\tRead Item\x90\x02\x01\x12q\n" +
	"\n" +
	"UpsertItem\x12'.listah.v1.ItemServiceUpsertItemRequest\x1a(.listah.v1.ItemServiceUpsertItemResponse\"\x10\xbaG\r\x1a\vUpsert Item\x12\x89\x01\n" +
	"\x0fReadTagProperty\x12,.listah.v1.ItemServiceReadTagPropertyRequest\x1a-.listah.v1.ItemServiceReadTagPropertyResponse\"\x19\xbaG\x13\x1a\x11Read Tag Property\x90\x02\x01\x12h\n" +
	"\aReadTag\x12$.listah.v1.ItemServiceReadTagRequest\x1a%.listah.v1.ItemServiceReadTagResponse\"\x10\xbaG\n" +
	"\x1a\bRead Tag\x90\x02\x01\x12m\n" +
	"\tUpsertTag\x12&.listah.v1.ItemServiceUpsertTagRequest\x1a'.listah.v1.ItemServiceUpsertTagResponse\"\x0f\xbaG\f\x1a\n" +
	"Upsert Tag\x12t\n" +
	"\n" +
	"ReadFilter\x12'.listah.v1.ItemServiceReadFilterRequest\x1a(.listah.v1.ItemServiceReadFilterResponse\"\x13\xbaG\r\x1a\vRead Filter\x90\x02\x01\x12y\n" +
	"\fUpsertFilter\x12).listah.v1.ItemServiceUpsertFilterRequest\x1a*.listah.v1.ItemServiceUpsertFilterResponse\"\x12\xbaG\x0f\x1a\rUpsert FilterB)Z'cornucopia/listah/internal/pkg/proto/v1b\x06proto3"

var (
	file_v1_item_proto_rawDescOnce sync.Once
	file_v1_item_proto_rawDescData []byte
)

func file_v1_item_proto_rawDescGZIP() []byte {
	file_v1_item_proto_rawDescOnce.Do(func() {
		file_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_item_proto_rawDesc), len(file_v1_item_proto_rawDesc)))
	})
	return file_v1_item_proto_rawDescData
}

var file_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_item_proto_goTypes = []any{
	(*ItemServiceReadItemRequest)(nil),         // 0: listah.v1.ItemServiceReadItemRequest
	(*ItemServiceReadItemResponse)(nil),        // 1: listah.v1.ItemServiceReadItemResponse
	(*ItemServiceUpsertItemRequest)(nil),       // 2: listah.v1.ItemServiceUpsertItemRequest
	(*ItemServiceUpsertItemResponse)(nil),      // 3: listah.v1.ItemServiceUpsertItemResponse
	(*ItemServiceReadTagRequest)(nil),          // 4: listah.v1.ItemServiceReadTagRequest
	(*ItemServiceReadTagResponse)(nil),         // 5: listah.v1.ItemServiceReadTagResponse
	(*ItemServiceUpsertTagRequest)(nil),        // 6: listah.v1.ItemServiceUpsertTagRequest
	(*ItemServiceUpsertTagResponse)(nil),       // 7: listah.v1.ItemServiceUpsertTagResponse
	(*ItemServiceReadTagPropertyRequest)(nil),  // 8: listah.v1.ItemServiceReadTagPropertyRequest
	(*ItemServiceReadTagPropertyResponse)(nil), // 9: listah.v1.ItemServiceReadTagPropertyResponse
	(*ItemServiceReadFilterRequest)(nil),       // 10: listah.v1.ItemServiceReadFilterRequest
	(*ItemServiceReadFilterResponse)(nil),      // 11: listah.v1.ItemServiceReadFilterResponse
	(*ItemServiceUpsertFilterRequest)(nil),     // 12: listah.v1.ItemServiceUpsertFilterRequest
	(*ItemServiceUpsertFilterResponse)(nil),    // 13: listah.v1.ItemServiceUpsertFilterResponse
	nil,                                        // 14: listah.v1.ItemServiceReadTagResponse.TagidPropMapEntry
	nil,                                        // 15: listah.v1.ItemServiceReadTagPropertyResponse.PropsEntry
	(*Search)(nil),                             // 16: listah.v1.Search
	(*Pagination)(nil),                         // 17: listah.v1.Pagination
	(*Item)(nil),                               // 18: listah.v1.Item
	(*Tag)(nil),                                // 19: listah.v1.Tag
	(*Filter)(nil),                             // 20: listah.v1.Filter
	(*StringList)(nil),                         // 21: listah.v1.StringList
}
var file_v1_item_proto_depIdxs = []int32{
	16, // 0: listah.v1.ItemServiceReadItemRequest.query:type_name -> listah.v1.Search
	17, // 1: listah.v1.ItemServiceReadItemRequest.pagination:type_name -> listah.v1.Pagination
	18, // 2: listah.v1.ItemServiceReadItemResponse.items:type_name -> listah.v1.Item
	16, // 3: listah.v1.ItemServiceReadItemResponse.query:type_name -> listah.v1.Search
	17, // 4: listah.v1.ItemServiceReadItemResponse.pagination:type_name -> listah.v1.Pagination
	18, // 5: listah.v1.ItemServiceUpsertItemRequest.items:type_name -> listah.v1.Item
	16, // 6: listah.v1.ItemServiceReadTagRequest.query:type_name -> listah.v1.Search
	17, // 7: listah.v1.ItemServiceReadTagRequest.pagination:type_name -> listah.v1.Pagination
	19, // 8: listah.v1.ItemServiceReadTagResponse.tags:type_name -> listah.v1.Tag
	14, // 9: listah.v1.ItemServiceReadTagResponse.tagidPropMap:type_name -> listah.v1.ItemServiceReadTagResponse.TagidPropMapEntry
	16, // 10: listah.v1.ItemServiceReadTagResponse.query:type_name -> listah.v1.Search
	17, // 11: listah.v1.ItemServiceReadTagResponse.pagination:type_name -> listah.v1.Pagination
	19, // 12: listah.v1.ItemServiceUpsertTagRequest.tags:type_name -> listah.v1.Tag
	16, // 13: listah.v1.ItemServiceReadTagPropertyRequest.query:type_name -> listah.v1.Search
	17, // 14: listah.v1.ItemServiceReadTagPropertyRequest.pagination:type_name -> listah.v1.Pagination
	15, // 15: listah.v1.ItemServiceReadTagPropertyResponse.props:type_name -> listah.v1.ItemServiceReadTagPropertyResponse.PropsEntry
	16, // 16: listah.v1.ItemServiceReadTagPropertyResponse.query:type_name -> listah.v1.Search
	17, // 17: listah.v1.ItemServiceReadTagPropertyResponse.pagination:type_name -> listah.v1.Pagination
	16, // 18: listah.v1.ItemServiceReadFilterRequest.query:type_name -> listah.v1.Search
	17, // 19: listah.v1.ItemServiceReadFilterRequest.pagination:type_name -> listah.v1.Pagination
	20, // 20: listah.v1.ItemServiceReadFilterResponse.filters:type_name -> listah.v1.Filter
	16, // 21: listah.v1.ItemServiceReadFilterResponse.query:type_name -> listah.v1.Search
	17, // 22: listah.v1.ItemServiceReadFilterResponse.pagination:type_name -> listah.v1.Pagination
	20, // 23: listah.v1.ItemServiceUpsertFilterRequest.filters:type_name -> listah.v1.Filter
	21, // 24: listah.v1.ItemServiceReadTagResponse.TagidPropMapEntry.value:type_name -> listah.v1.StringList
	21, // 25: listah.v1.ItemServiceReadTagPropertyResponse.PropsEntry.value:type_name -> listah.v1.StringList
	0,  // 26: listah.v1.ItemService.ReadItem:input_type -> listah.v1.ItemServiceReadItemRequest
	2,  // 27: listah.v1.ItemService.UpsertItem:input_type -> listah.v1.ItemServiceUpsertItemRequest
	8,  // 28: listah.v1.ItemService.ReadTagProperty:input_type -> listah.v1.ItemServiceReadTagPropertyRequest
	4,  // 29: listah.v1.ItemService.ReadTag:input_type -> listah.v1.ItemServiceReadTagRequest
	6,  // 30: listah.v1.ItemService.UpsertTag:input_type -> listah.v1.ItemServiceUpsertTagRequest
	10, // 31: listah.v1.ItemService.ReadFilter:input_type -> listah.v1.ItemServiceReadFilterRequest
	12, // 32: listah.v1.ItemService.UpsertFilter:input_type -> listah.v1.ItemServiceUpsertFilterRequest
	1,  // 33: listah.v1.ItemService.ReadItem:output_type -> listah.v1.ItemServiceReadItemResponse
	3,  // 34: listah.v1.ItemService.UpsertItem:output_type -> listah.v1.ItemServiceUpsertItemResponse
	9,  // 35: listah.v1.ItemService.ReadTagProperty:output_type -> listah.v1.ItemServiceReadTagPropertyResponse
	5,  // 36: listah.v1.ItemService.ReadTag:output_type -> listah.v1.ItemServiceReadTagResponse
	7,  // 37: listah.v1.ItemService.UpsertTag:output_type -> listah.v1.ItemServiceUpsertTagResponse
	11, // 38: listah.v1.ItemService.ReadFilter:output_type -> listah.v1.ItemServiceReadFilterResponse
	13, // 39: listah.v1.ItemService.UpsertFilter:output_type -> listah.v1.ItemServiceUpsertFilterResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_v1_item_proto_init() }
func file_v1_item_proto_init() {
	if File_v1_item_proto != nil {
		return
	}
	file_v1_commons_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_item_proto_rawDesc), len(file_v1_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_item_proto_goTypes,
		DependencyIndexes: file_v1_item_proto_depIdxs,
		MessageInfos:      file_v1_item_proto_msgTypes,
	}.Build()
	File_v1_item_proto = out.File
	file_v1_item_proto_goTypes = nil
	file_v1_item_proto_depIdxs = nil
}
