databaseChangeLog:
 - includeAll:
     path: migrations/
     relativeToChangelogFile: true
     endsWithFilter: .xml
 - includeAll:
     path: migrations/
     relativeToChangelogFile: true
     endsWithFilter: .yaml

