// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/filter.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "cornucopia/listah/apps/api/internal/pkg/proto/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilterServiceName is the fully-qualified name of the FilterService service.
	FilterServiceName = "listah.v1.FilterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilterServiceReadCategoryProcedure is the fully-qualified name of the FilterService's
	// ReadCategory RPC.
	FilterServiceReadCategoryProcedure = "/listah.v1.FilterService/ReadCategory"
	// FilterServiceReadItemProcedure is the fully-qualified name of the FilterService's ReadItem RPC.
	FilterServiceReadItemProcedure = "/listah.v1.FilterService/ReadItem"
)

// FilterServiceClient is a client for the listah.v1.FilterService service.
type FilterServiceClient interface {
	ReadCategory(context.Context, *connect.Request[v1.FilterServiceCategoryReadRequest]) (*connect.Response[v1.FilterServiceCategoryReadResponse], error)
	ReadItem(context.Context, *connect.Request[v1.FilterServiceItemReadRequest]) (*connect.Response[v1.FilterServiceItemReadResponse], error)
}

// NewFilterServiceClient constructs a client for the listah.v1.FilterService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filterServiceMethods := v1.File_v1_filter_proto.Services().ByName("FilterService").Methods()
	return &filterServiceClient{
		readCategory: connect.NewClient[v1.FilterServiceCategoryReadRequest, v1.FilterServiceCategoryReadResponse](
			httpClient,
			baseURL+FilterServiceReadCategoryProcedure,
			connect.WithSchema(filterServiceMethods.ByName("ReadCategory")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		readItem: connect.NewClient[v1.FilterServiceItemReadRequest, v1.FilterServiceItemReadResponse](
			httpClient,
			baseURL+FilterServiceReadItemProcedure,
			connect.WithSchema(filterServiceMethods.ByName("ReadItem")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// filterServiceClient implements FilterServiceClient.
type filterServiceClient struct {
	readCategory *connect.Client[v1.FilterServiceCategoryReadRequest, v1.FilterServiceCategoryReadResponse]
	readItem     *connect.Client[v1.FilterServiceItemReadRequest, v1.FilterServiceItemReadResponse]
}

// ReadCategory calls listah.v1.FilterService.ReadCategory.
func (c *filterServiceClient) ReadCategory(ctx context.Context, req *connect.Request[v1.FilterServiceCategoryReadRequest]) (*connect.Response[v1.FilterServiceCategoryReadResponse], error) {
	return c.readCategory.CallUnary(ctx, req)
}

// ReadItem calls listah.v1.FilterService.ReadItem.
func (c *filterServiceClient) ReadItem(ctx context.Context, req *connect.Request[v1.FilterServiceItemReadRequest]) (*connect.Response[v1.FilterServiceItemReadResponse], error) {
	return c.readItem.CallUnary(ctx, req)
}

// FilterServiceHandler is an implementation of the listah.v1.FilterService service.
type FilterServiceHandler interface {
	ReadCategory(context.Context, *connect.Request[v1.FilterServiceCategoryReadRequest]) (*connect.Response[v1.FilterServiceCategoryReadResponse], error)
	ReadItem(context.Context, *connect.Request[v1.FilterServiceItemReadRequest]) (*connect.Response[v1.FilterServiceItemReadResponse], error)
}

// NewFilterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilterServiceHandler(svc FilterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filterServiceMethods := v1.File_v1_filter_proto.Services().ByName("FilterService").Methods()
	filterServiceReadCategoryHandler := connect.NewUnaryHandler(
		FilterServiceReadCategoryProcedure,
		svc.ReadCategory,
		connect.WithSchema(filterServiceMethods.ByName("ReadCategory")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	filterServiceReadItemHandler := connect.NewUnaryHandler(
		FilterServiceReadItemProcedure,
		svc.ReadItem,
		connect.WithSchema(filterServiceMethods.ByName("ReadItem")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/listah.v1.FilterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilterServiceReadCategoryProcedure:
			filterServiceReadCategoryHandler.ServeHTTP(w, r)
		case FilterServiceReadItemProcedure:
			filterServiceReadItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilterServiceHandler struct{}

func (UnimplementedFilterServiceHandler) ReadCategory(context.Context, *connect.Request[v1.FilterServiceCategoryReadRequest]) (*connect.Response[v1.FilterServiceCategoryReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.FilterService.ReadCategory is not implemented"))
}

func (UnimplementedFilterServiceHandler) ReadItem(context.Context, *connect.Request[v1.FilterServiceItemReadRequest]) (*connect.Response[v1.FilterServiceItemReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.FilterService.ReadItem is not implemented"))
}
