// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/item.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "cornucopia/listah/internal/pkg/proto/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ItemServiceName is the fully-qualified name of the ItemService service.
	ItemServiceName = "listah.v1.ItemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ItemServiceCreateItemProcedure is the fully-qualified name of the ItemService's CreateItem RPC.
	ItemServiceCreateItemProcedure = "/listah.v1.ItemService/CreateItem"
	// ItemServiceReadItemProcedure is the fully-qualified name of the ItemService's ReadItem RPC.
	ItemServiceReadItemProcedure = "/listah.v1.ItemService/ReadItem"
	// ItemServiceUpsertItemProcedure is the fully-qualified name of the ItemService's UpsertItem RPC.
	ItemServiceUpsertItemProcedure = "/listah.v1.ItemService/UpsertItem"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	itemServiceServiceDescriptor          = v1.File_v1_item_proto.Services().ByName("ItemService")
	itemServiceCreateItemMethodDescriptor = itemServiceServiceDescriptor.Methods().ByName("CreateItem")
	itemServiceReadItemMethodDescriptor   = itemServiceServiceDescriptor.Methods().ByName("ReadItem")
	itemServiceUpsertItemMethodDescriptor = itemServiceServiceDescriptor.Methods().ByName("UpsertItem")
)

// ItemServiceClient is a client for the listah.v1.ItemService service.
type ItemServiceClient interface {
	CreateItem(context.Context, *connect.Request[v1.ItemServiceCreateItemRequest]) (*connect.Response[v1.ItemServiceCreateItemResponse], error)
	ReadItem(context.Context, *connect.Request[v1.ItemServiceReadItemRequest]) (*connect.Response[v1.ItemServiceReadItemResponse], error)
	UpsertItem(context.Context, *connect.Request[v1.ItemServiceUpsertItemRequest]) (*connect.Response[v1.ItemServiceUpsertItemResponse], error)
}

// NewItemServiceClient constructs a client for the listah.v1.ItemService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewItemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ItemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &itemServiceClient{
		createItem: connect.NewClient[v1.ItemServiceCreateItemRequest, v1.ItemServiceCreateItemResponse](
			httpClient,
			baseURL+ItemServiceCreateItemProcedure,
			connect.WithSchema(itemServiceCreateItemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		readItem: connect.NewClient[v1.ItemServiceReadItemRequest, v1.ItemServiceReadItemResponse](
			httpClient,
			baseURL+ItemServiceReadItemProcedure,
			connect.WithSchema(itemServiceReadItemMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		upsertItem: connect.NewClient[v1.ItemServiceUpsertItemRequest, v1.ItemServiceUpsertItemResponse](
			httpClient,
			baseURL+ItemServiceUpsertItemProcedure,
			connect.WithSchema(itemServiceUpsertItemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// itemServiceClient implements ItemServiceClient.
type itemServiceClient struct {
	createItem *connect.Client[v1.ItemServiceCreateItemRequest, v1.ItemServiceCreateItemResponse]
	readItem   *connect.Client[v1.ItemServiceReadItemRequest, v1.ItemServiceReadItemResponse]
	upsertItem *connect.Client[v1.ItemServiceUpsertItemRequest, v1.ItemServiceUpsertItemResponse]
}

// CreateItem calls listah.v1.ItemService.CreateItem.
func (c *itemServiceClient) CreateItem(ctx context.Context, req *connect.Request[v1.ItemServiceCreateItemRequest]) (*connect.Response[v1.ItemServiceCreateItemResponse], error) {
	return c.createItem.CallUnary(ctx, req)
}

// ReadItem calls listah.v1.ItemService.ReadItem.
func (c *itemServiceClient) ReadItem(ctx context.Context, req *connect.Request[v1.ItemServiceReadItemRequest]) (*connect.Response[v1.ItemServiceReadItemResponse], error) {
	return c.readItem.CallUnary(ctx, req)
}

// UpsertItem calls listah.v1.ItemService.UpsertItem.
func (c *itemServiceClient) UpsertItem(ctx context.Context, req *connect.Request[v1.ItemServiceUpsertItemRequest]) (*connect.Response[v1.ItemServiceUpsertItemResponse], error) {
	return c.upsertItem.CallUnary(ctx, req)
}

// ItemServiceHandler is an implementation of the listah.v1.ItemService service.
type ItemServiceHandler interface {
	CreateItem(context.Context, *connect.Request[v1.ItemServiceCreateItemRequest]) (*connect.Response[v1.ItemServiceCreateItemResponse], error)
	ReadItem(context.Context, *connect.Request[v1.ItemServiceReadItemRequest]) (*connect.Response[v1.ItemServiceReadItemResponse], error)
	UpsertItem(context.Context, *connect.Request[v1.ItemServiceUpsertItemRequest]) (*connect.Response[v1.ItemServiceUpsertItemResponse], error)
}

// NewItemServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewItemServiceHandler(svc ItemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	itemServiceCreateItemHandler := connect.NewUnaryHandler(
		ItemServiceCreateItemProcedure,
		svc.CreateItem,
		connect.WithSchema(itemServiceCreateItemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceReadItemHandler := connect.NewUnaryHandler(
		ItemServiceReadItemProcedure,
		svc.ReadItem,
		connect.WithSchema(itemServiceReadItemMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceUpsertItemHandler := connect.NewUnaryHandler(
		ItemServiceUpsertItemProcedure,
		svc.UpsertItem,
		connect.WithSchema(itemServiceUpsertItemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/listah.v1.ItemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ItemServiceCreateItemProcedure:
			itemServiceCreateItemHandler.ServeHTTP(w, r)
		case ItemServiceReadItemProcedure:
			itemServiceReadItemHandler.ServeHTTP(w, r)
		case ItemServiceUpsertItemProcedure:
			itemServiceUpsertItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedItemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedItemServiceHandler struct{}

func (UnimplementedItemServiceHandler) CreateItem(context.Context, *connect.Request[v1.ItemServiceCreateItemRequest]) (*connect.Response[v1.ItemServiceCreateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.ItemService.CreateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) ReadItem(context.Context, *connect.Request[v1.ItemServiceReadItemRequest]) (*connect.Response[v1.ItemServiceReadItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.ItemService.ReadItem is not implemented"))
}

func (UnimplementedItemServiceHandler) UpsertItem(context.Context, *connect.Request[v1.ItemServiceUpsertItemRequest]) (*connect.Response[v1.ItemServiceUpsertItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.ItemService.UpsertItem is not implemented"))
}
