// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/tag.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "cornucopia/listah/apps/api/internal/pkg/proto/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TagServiceName is the fully-qualified name of the TagService service.
	TagServiceName = "listah.v1.TagService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TagServiceReadCategoryProcedure is the fully-qualified name of the TagService's ReadCategory RPC.
	TagServiceReadCategoryProcedure = "/listah.v1.TagService/ReadCategory"
	// TagServiceReadItemProcedure is the fully-qualified name of the TagService's ReadItem RPC.
	TagServiceReadItemProcedure = "/listah.v1.TagService/ReadItem"
)

// TagServiceClient is a client for the listah.v1.TagService service.
type TagServiceClient interface {
	ReadCategory(context.Context, *connect.Request[v1.TagServiceCategoryReadRequest]) (*connect.Response[v1.TagServiceCategoryReadResponse], error)
	ReadItem(context.Context, *connect.Request[v1.TagServiceItemReadRequest]) (*connect.Response[v1.TagServiceItemReadResponse], error)
}

// NewTagServiceClient constructs a client for the listah.v1.TagService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTagServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TagServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tagServiceMethods := v1.File_v1_tag_proto.Services().ByName("TagService").Methods()
	return &tagServiceClient{
		readCategory: connect.NewClient[v1.TagServiceCategoryReadRequest, v1.TagServiceCategoryReadResponse](
			httpClient,
			baseURL+TagServiceReadCategoryProcedure,
			connect.WithSchema(tagServiceMethods.ByName("ReadCategory")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		readItem: connect.NewClient[v1.TagServiceItemReadRequest, v1.TagServiceItemReadResponse](
			httpClient,
			baseURL+TagServiceReadItemProcedure,
			connect.WithSchema(tagServiceMethods.ByName("ReadItem")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// tagServiceClient implements TagServiceClient.
type tagServiceClient struct {
	readCategory *connect.Client[v1.TagServiceCategoryReadRequest, v1.TagServiceCategoryReadResponse]
	readItem     *connect.Client[v1.TagServiceItemReadRequest, v1.TagServiceItemReadResponse]
}

// ReadCategory calls listah.v1.TagService.ReadCategory.
func (c *tagServiceClient) ReadCategory(ctx context.Context, req *connect.Request[v1.TagServiceCategoryReadRequest]) (*connect.Response[v1.TagServiceCategoryReadResponse], error) {
	return c.readCategory.CallUnary(ctx, req)
}

// ReadItem calls listah.v1.TagService.ReadItem.
func (c *tagServiceClient) ReadItem(ctx context.Context, req *connect.Request[v1.TagServiceItemReadRequest]) (*connect.Response[v1.TagServiceItemReadResponse], error) {
	return c.readItem.CallUnary(ctx, req)
}

// TagServiceHandler is an implementation of the listah.v1.TagService service.
type TagServiceHandler interface {
	ReadCategory(context.Context, *connect.Request[v1.TagServiceCategoryReadRequest]) (*connect.Response[v1.TagServiceCategoryReadResponse], error)
	ReadItem(context.Context, *connect.Request[v1.TagServiceItemReadRequest]) (*connect.Response[v1.TagServiceItemReadResponse], error)
}

// NewTagServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTagServiceHandler(svc TagServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tagServiceMethods := v1.File_v1_tag_proto.Services().ByName("TagService").Methods()
	tagServiceReadCategoryHandler := connect.NewUnaryHandler(
		TagServiceReadCategoryProcedure,
		svc.ReadCategory,
		connect.WithSchema(tagServiceMethods.ByName("ReadCategory")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceReadItemHandler := connect.NewUnaryHandler(
		TagServiceReadItemProcedure,
		svc.ReadItem,
		connect.WithSchema(tagServiceMethods.ByName("ReadItem")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/listah.v1.TagService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TagServiceReadCategoryProcedure:
			tagServiceReadCategoryHandler.ServeHTTP(w, r)
		case TagServiceReadItemProcedure:
			tagServiceReadItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTagServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTagServiceHandler struct{}

func (UnimplementedTagServiceHandler) ReadCategory(context.Context, *connect.Request[v1.TagServiceCategoryReadRequest]) (*connect.Response[v1.TagServiceCategoryReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.TagService.ReadCategory is not implemented"))
}

func (UnimplementedTagServiceHandler) ReadItem(context.Context, *connect.Request[v1.TagServiceItemReadRequest]) (*connect.Response[v1.TagServiceItemReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listah.v1.TagService.ReadItem is not implemented"))
}
