
name: Build Api App
run-name: Build Api App to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build_api:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: 'apps/api'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      API_IMAGE_NAME_TAG: ${{ vars.APP_NAME }}-api:${GITHUB_SHA::7}
      WEB_IMAGE_NAME_TAG: ${{ vars.APP_NAME }}-web:${GITHUB_SHA::7}

      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_gcp_region: ${{ vars.GCP_REGION }}
      TF_VAR_state_management_bucket_name: ${{ secrets.STATE_MANAGEMENT_BUCKET_NAME }}
      TF_VAR_state_management_prefix: gcp/${{ inputs.environment }}
      TF_VAR_project: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_LOG: DEBUG

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_SERVICE_ACCOUNT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCP Artifact Registry
        run: |-
            gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      # The api needs the db certs from the output of the data job
      #     to be able to access the database.
      - name: Retrieve Outputs from Data Job Using Tofu Output
        run: |
          echo "pwd - $(pwd)"
          cd ${{ github.workspace }}/deployment/gcp/data
          tofu init

          echo "DB_CERTS="$(tofu output -raw db_client_cert)"" >> ${GITHUB_ENV}
          echo "REPO_URI="$(tofu output -raw artifact_repo_uri)"" >> ${GITHUB_ENV}
          echo "pwd - $(pwd)"

      - name: Build, Tag, and Push Docker Api Image to Container Repository Using Tofu Output
        run: |-
          echo "pwd - $(pwd)"
          echo "repo_uri - ${{ env.REPO_URI }}"
          echo "api_image_name - ${{ env.API_IMAGE_NAME_TAG }}"
          api_image_full_name="${{ env.REPO_URI }}/${{ env.API_IMAGE_NAME_TAG }}"
          echo "API_IMAGE_FULL_NAME="${api_image_full_name}"" >> ${GITHUB_ENV}
          echo "api_image_full_name - ${api_image_full_name}"

          echo "${{ env.DB_CERTS }}" > ./db_ca.crt
          docker build . -t "${api_image_full_name}"
          docker push "${api_image_full_name}"
          echo "pwd - $(pwd)"
