
name: Deploy App Infra
run-name: Deploy App Infra to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: 'deployment/gcp/api'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      API_IMAGE_NAME: ${{ vars.APP_NAME }}-api
      WEB_IMAGE_NAME: ${{ vars.APP_NAME }}-web

      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_gcp_region: ${{ vars.GCP_REGION }}
      TF_VAR_state_management_bucket_name: ${{ secrets.STATE_MANAGEMENT_BUCKET_NAME }}
      TF_VAR_state_management_prefix: gcp/${{ inputs.environment }}
      TF_VAR_project: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_LOG: DEBUG

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_SERVICE_ACCOUNT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCP Artifact Registry
        run: |-
            gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      # The api needs the db certs from the output of the data job
      #     to be able to access the database.
      - name: Retrieve Outputs from Data Job Using Tofu Output
        run: |
          echo "pwd - $(pwd)"
          cd ${{ github.workspace }}/deployment/gcp/data
          tofu init

          echo "REPO_URI="$(tofu output -raw artifact_repo_uri)"" >> ${GITHUB_ENV}
          echo "pwd - $(pwd)"

      - name: Retrieve latest Api Tag
        run: |
          LATEST_DIGEST=$(gcloud artifacts docker images list \
          ${{ env.REPO_URI }}/${{ env.API_IMAGE_NAME }} \
            --sort-by="~UPDATE_TIME"  \
            --limit=1 \
            --format="value(DIGEST)" \
          )
          echo "LATEST_DIGEST: ${LATEST_DIGEST}"

          LATEST_TAG=$(gcloud artifacts docker tags list \
          ${{ env.REPO_URI }}/${{ env.API_IMAGE_NAME }} \
            --filter="DIGEST:${LATEST_DIGEST}" \
            --format="value(TAG)"
          )
          echo "LATEST_TAG: ${LATEST_TAG}"

          IMAGE_NAME_TAG="${{ env.REPO_URI }}/${{ env.API_IMAGE_NAME }}:${LATEST_TAG}"
          echo "IMAGE_NAME_TAG: ${IMAGE_NAME_TAG}"

          echo "API_LATEST_TAG="${LATEST_TAG}"" >> ${GITHUB_ENV}
          echo "API_IMAGE_NAME_TAG="${IMAGE_NAME_TAG}"" >> ${GITHUB_ENV}

      - name: Initialise, Check, Validate, Plan and Apply OpenTofu for Api
        run: |-
          tofu fmt -check
          tofu init
          tofu validate
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan
        env:
          TF_VAR_image_tag: ${{ env.API_IMAGE_NAME_TAG }}
          TF_VAR_known_origins: "a,b,c"
          # ToDo: change known origins
