import type { Metadata } from "next";
import * as React from 'react';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import { Geist, Geist_Mono } from "next/font/google";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import '@/envConfig.ts';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <React.Fragment>
      <CssBaseline />
      <ClerkProvider>
        <html lang="en">
          <head>
          </head>
          <body>
            <Box sx={{ bgcolor: '#cfe8fc', height: '100vh' }}>
            {/* <Box sx={{ bgcolor: 'green', height: '100vh' }}> */}
              <Container maxWidth="l">
                {children}
              </Container>
            </Box>
          </body>
        </html>
      </ClerkProvider>
    </React.Fragment>

  );
}
