databaseChangeLog:
  - preConditions:
      - runningAs:
          username:  listah-admin
  - changeSet:
        id:  "1.0.0"
        author:  "Kelechi Berquist"
        labels: "root-migration"
        context: "0.0.0"
        comment: "Initial migration"
        changes:
        - createTable:
              schemaName: apps
              tableName:  items
              ifNotExists: true
              columns:
                - column:
                    name:  id
                    type:  varchar
                    constraints:
                      primaryKey:  true
                      nullable:  false
                - column:
                    name:  user_id
                    type:  varchar
                    constraints:
                      nullable:  false
                - column:
                    name:  summary
                    type:  varchar
                - column:
                    name:  category
                    type:  varchar
                - column:
                    name:  description
                    type:  varchar
                - column:
                    name:  note
                    type:  varchar
                - column:
                    name:  tags
                    type:  json
                - column:
                    name:  properties
                    type:  json
                - column:
                    name:  reactivate_at
                    type:  timestamp
                - column:
                    name:  audit
                    type:  json

        - createTable:
              schemaName: instrumentation
              tableName:  apiLogs
              columns:
                - column:
                    name:  id
                    type:  varchar
                    constraints:
                      primaryKey:  true
                      nullable:  false
                - column:
                    name:  request_source
                    type:  varchar
                - column:
                    name:  trace_id
                    type:  varchar
                - column:
                    name:  span_id
                    type:  varchar
                - column:
                    name:  request
                    type:  json
                    constraints:
                      nullable:  false
                - column:
                    name:  request_time
                    type:  timestamp
